
import { useMemo, useState, useEffect } from "react";
import {
  Banknote,
  CalendarDays,
  Download,
  Printer,
  ShieldCheck,
  UserRound,
  FileText,
  CheckCircle2,
  Building2,
  AlertCircle,
} from "lucide-react";
import { PrimaryButton } from "./shared/ui.jsx";
import { supabase, isSupabaseConfigured } from "../../lib/supabaseClient";

const COMPANY = {
  name: import.meta.env.VITE_COMPANY_NAME || "Company",
  addressLine1:
    import.meta.env.VITE_COMPANY_ADDRESS_LINE1 || "Payslip generated by HRMS",
  logoUrl: import.meta.env.VITE_COMPANY_LOGO || "",
};

const money = (n) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(n);

const isDmy = (value) => /^\d{2}\/\d{2}\/\d{4}$/.test(value);

const formatDateValue = (value) => {
  const raw = String(value || "").trim();
  if (!raw) return "-";
  if (isDmy(raw)) return raw;
  const d = new Date(raw);
  if (Number.isNaN(d.getTime())) return raw;
  const dd = String(d.getDate()).padStart(2, "0");
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const yy = String(d.getFullYear());
  return `${dd}/${mm}/${yy}`;
};

// Format month from YYYY-MM to MM/YYYY
const formatMonthDisplay = (monthKey) => {
  if (!monthKey || !monthKey.includes("-")) return monthKey;
  const [year, month] = monthKey.split("-");
  return `${month}/${year}`;
};

const maskAccount = (value) => {
  const raw = String(value || "").trim();
  if (!raw) return "-";
  const last4 = raw.slice(-4);
  return `**** ${last4}`;
};

function numberToWords(n) {
  const ones = [
    "Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
    "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen",
  ];
  const tens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"];

  const toWordsBelow100 = (x) => {
    if (x < 20) return ones[x];
    const t = Math.floor(x / 10);
    const o = x % 10;
    return tens[t] + (o ? " " + ones[o] : "");
  };

  const toWordsBelow1000 = (x) => {
    const h = Math.floor(x / 100);
    const r = x % 100;
    if (!h) return toWordsBelow100(r);
    if (!r) return ones[h] + " Hundred";
    return ones[h] + " Hundred " + toWordsBelow100(r);
  };

  const num = Math.floor(Number(n || 0));
  if (Number.isNaN(num)) return "";
  if (num === 0) return "Zero";
  if (num < 1000) return toWordsBelow1000(num);

  const crore = Math.floor(num / 10000000);
  const lakh = Math.floor((num % 10000000) / 100000);
  const thousand = Math.floor((num % 100000) / 1000);
  const rest = num % 1000;

  const parts = [];
  if (crore) parts.push(toWordsBelow1000(crore) + " Crore");
  if (lakh) parts.push(toWordsBelow1000(lakh) + " Lakh");
  if (thousand) parts.push(toWordsBelow1000(thousand) + " Thousand");
  if (rest) parts.push(toWordsBelow1000(rest));

  return parts.join(" ");
}

const MonthCard = ({ label, selected, onClick, paidOn }) => (
  <button
    onClick={onClick}
    className={`w-full text-left rounded-2xl border px-4 py-3 shadow-sm transition ${selected
      ? "border-indigo-300 bg-indigo-50"
      : "border-slate-200 bg-white hover:bg-slate-50"
      }`}
  >
    <div className="flex items-center justify-between">
      <div>
        <p className="text-sm font-extrabold text-slate-900">{formatMonthDisplay(label)}</p>
        <p className="text-xs text-slate-500">Paid on {formatMonthDisplay(paidOn)}</p>
      </div>
      {selected ? (
        <span className="text-[11px] font-semibold text-indigo-700">
          Viewing
        </span>
      ) : (
        <span className="text-[11px] font-semibold text-slate-500">Open</span>
      )}
    </div>
  </button>
);

const Pill = ({ label, value }) => (
  <div className="rounded-xl border bg-white px-4 py-3 text-center shadow-sm">
    <p className="text-xs font-semibold text-slate-500 uppercase">{label}</p>
    <p className="mt-1 text-lg font-extrabold text-slate-900">{value}</p>
  </div>
);

export default function EmployeePayslips() {

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [payslipData, setPayslipData] = useState({});
  const [selected, setSelected] = useState("");

  const months = useMemo(() => Object.keys(payslipData), [payslipData]);
  const data = payslipData[selected] || (months.length > 0 ? payslipData[months[0]] : null);

  useEffect(() => {
    async function fetchData() {
      try {
        setLoading(true);
        setError(null);

        const authSession = JSON.parse(localStorage.getItem("HRMSS_AUTH_SESSION") || "{}");
        const employeeId = authSession.employee_id || authSession.id || authSession.identifier;

        if (!employeeId) {
          throw new Error("User session not found. Please login again.");
        }

        if (!isSupabaseConfigured) {
          throw new Error("Database not configured.");
        }

        // 1. Fetch Employee Details + Profile Bank Details
        const [{ data: emp, error: empErr }, { data: profile, error: profErr }] = await Promise.all([
          supabase
            .from("hrmss_employees")
            .select("*")
            .eq("employee_id", employeeId)
            .maybeSingle(),
          supabase
            .from("hrmss_employee_profiles")
            .select("bank_name, account_number, ifsc_code, branch, account_holder_name")
            .eq("employee_id", employeeId)
            .maybeSingle()
        ]);

        if (empErr) throw empErr;

        // 2. Fetch Payroll Data
        const { data: payroll, error: payErr } = await supabase
          .from("hrmss_payroll")
          .select("*")
          .eq("employee_id", employeeId)
          .order("month", { ascending: false });

        if (payErr) throw payErr;

        if (!payroll || payroll.length === 0) {
          setPayslipData({});
          setLoading(false);
          return;
        }

        // 3. Map to payslipData format
        const mappedData = {};
        payroll.forEach((p) => {
          const monthKey = p.month || "Unknown";
          const basic = Number(p.basic_salary || 0);
          const hra = Number(p.hra || 0);
          const conveyance = Number(p.conveyance_allowance || 0);
          const medical = Number(p.medical_allowance || 0);
          const special = Number(p.special_allowance || 0);
          const earningsTotal = basic + hra + conveyance + medical + special;
          const deductionsTotal =
            Number(p.pf_employee || 0) +
            Number(p.esi_employee || 0) +
            Number(p.professional_tax || 0);
          const net =
            Number(p.net_salary ?? Math.max(earningsTotal - deductionsTotal, 0));

          mappedData[monthKey] = {
            month: monthKey,
            employee: {
              name: emp?.full_name || "Unknown",
              id: emp?.employee_id || employeeId,
              designation: emp?.role || emp?.designation || "-",
              department: emp?.department || "-",
              doj: emp?.join_date || "-",
            },
            earnings: [
              { label: "Basic Salary", value: basic },
              { label: "House Rent Allowance (HRA)", value: hra },
              { label: "Conveyance Allowance", value: conveyance },
              { label: "Medical Allowance", value: medical },
              { label: "Special Allowance", value: special },
            ],
            deductions: [
              { label: "PF Contribution (Employee)", value: p.pf_employee || 0 },
              { label: "ESI Contribution (Employee)", value: p.esi_employee || 0 },
              { label: "Professional Tax", value: p.professional_tax || 0 },
            ],
            attendance: {
              working: p.working_days || "-",
              present: p.present_days || "-",
              paidLeave: p.paid_leave || "-",
              lop: p.lop_days || "-"
            },
            bank: {
              holder: profile?.account_holder_name || emp?.full_name || "-",
              name: profile?.bank_name || emp?.bank_name || "-",
              account: maskAccount(profile?.account_number || emp?.account_number || ""),
              ifsc: profile?.ifsc_code || "-",
              branch: profile?.branch || "-",
              mode: p.payment_mode || "Bank Transfer",
              paidOn: monthKey,
            },
            paidOn: p.paid_on || p.created_at?.split("T")[0] || "-",
            totals: { earn: earningsTotal, ded: deductionsTotal, net },
          };
        });

        setPayslipData(mappedData);
        const firstMonth = Object.keys(mappedData)[0];
        if (firstMonth) setSelected(firstMonth);

      } catch (err) {
        console.error("Error fetching payslip:", err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }

    fetchData();
  }, []);

  const totals = useMemo(() => {
    if (!data) return { earn: 0, ded: 0, net: 0 };
    if (data?.totals) return data.totals;
    const earn = (data?.earnings || []).reduce((a, b) => a + b.value, 0);
    const ded = (data?.deductions || []).reduce((a, b) => a + b.value, 0);
    return { earn, ded, net: Math.max(earn - ded, 0) };
  }, [data]);


  const handlePrint = () => window.print();

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-indigo-600 border-t-transparent"></div>
        <p className="ml-3 text-slate-600">Loading your payslips...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded-3xl border border-rose-100 bg-rose-50 p-6 text-center">
        <AlertCircle className="mx-auto mb-3 text-rose-600" size={40} />
        <p className="text-lg font-bold text-rose-900">Unable to load payslips</p>
        <p className="text-sm text-rose-700">{error}</p>
      </div>
    );
  }

  if (months.length === 0) {
    return (
      <div className="rounded-3xl border border-slate-200 bg-white p-12 text-center">
        <Banknote className="mx-auto mb-4 text-slate-300" size={48} />
        <h3 className="text-xl font-bold text-slate-900">No Payslips Found</h3>
        <p className="mt-2 text-slate-500">You don't have any payslips available in the system yet.</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 xl:grid xl:grid-cols-3 xl:gap-6">
        <div className="space-y-3 xl:col-span-1">
          <div className="rounded-3xl border bg-white p-4 shadow-sm">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs font-semibold text-slate-500">
                  Payslip Months
                </p>
                <p className="text-lg font-extrabold text-slate-900">
                  Select a month
                </p>
              </div>
              <Banknote size={18} className="text-slate-500" />
            </div>
            <div className="mt-3 space-y-2">
              {months.map((m) => (
                <MonthCard
                  key={m}
                  label={m}
                  paidOn={payslipData[m].paidOn}
                  selected={selected === m}
                  onClick={() => setSelected(m)}
                />
              ))}
            </div>
          </div>
        </div>

        <div className="xl:col-span-2">
          <div className="overflow-hidden rounded-3xl border bg-white shadow-sm">
            <div className="bg-gradient-to-r from-[#2B4BD8] to-[#21408F] px-6 py-5 text-white">
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-start gap-3">
                  {COMPANY.logoUrl ? (
                    <img
                      src={COMPANY.logoUrl}
                      alt={COMPANY.name}
                      className="h-12 w-12 rounded-lg border border-white/20 object-contain bg-white/10"
                    />
                  ) : (
                    <div className="h-12 w-12 rounded-xl bg-white/15 grid place-items-center border border-white/10">
                      <FileText size={18} className="text-white" />
                    </div>
                  )}
                  <div className="min-w-0">
                    <p className="text-lg font-extrabold leading-tight">
                      {COMPANY.name}
                    </p>
                    <p className="text-[11px] font-semibold text-white/80">
                      {COMPANY.addressLine1 || "Payslip generated by HRMS"}
                    </p>
                  </div>
                </div>

                <div className="text-right">
                  <p className="text-[11px] font-bold text-white/80">
                    Payslip for
                  </p>
                  <p className="text-sm font-extrabold">{formatMonthDisplay(data?.month)}</p>
                </div>
              </div>
            </div>

            <div className="p-6 space-y-4">
              <div className="rounded-2xl border bg-white p-4">
                <div className="flex items-center gap-2">
                  <UserRound size={16} className="text-indigo-600" />
                  <p className="text-xs font-extrabold text-slate-900 uppercase">
                    Employee Details
                  </p>
                </div>

                <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-3">
                  <div>
                    <p className="text-[10px] font-bold text-slate-500">
                      Employee Name
                    </p>
                    <p className="text-sm font-extrabold text-slate-900">
                      {data?.employee?.name}
                    </p>
                  </div>
                  <div>
                    <p className="text-[10px] font-bold text-slate-500">
                      Employee ID
                    </p>
                    <p className="text-sm font-extrabold text-slate-900">
                      {data?.employee?.id}
                    </p>
                  </div>
                  <div>
                    <p className="text-[10px] font-bold text-slate-500">
                      Designation
                    </p>
                    <p className="text-sm font-extrabold text-slate-900">
                      {data?.employee?.designation || "-"}
                    </p>
                  </div>
                  <div>
                    <p className="text-[10px] font-bold text-slate-500">
                      Department
                    </p>
                    <p className="text-sm font-extrabold text-slate-900">
                      {data?.employee?.department || "-"}
                    </p>
                  </div>
                  <div>
                    <p className="text-[10px] font-bold text-slate-500">
                      Date of Joining
                    </p>
                    <p className="text-sm font-extrabold text-slate-900">
                      {formatDateValue(data?.employee?.doj)}
                    </p>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
                <div className="rounded-2xl border bg-white overflow-hidden">
                  <div className="px-4 py-3 border-b bg-emerald-50">
                    <p className="text-xs font-extrabold text-emerald-700 uppercase">
                      Earnings
                    </p>
                  </div>
                  <div className="p-4 space-y-3">
                    {(data?.earnings || []).map((item) => (
                      <div
                        key={item.label}
                        className="flex items-center justify-between text-sm"
                      >
                        <p className="text-slate-600 font-semibold">
                          {item.label}
                        </p>
                        <p className="text-slate-900 font-extrabold tabular-nums">
                          {money(item.value)}
                        </p>
                      </div>
                    ))}
                    <div className="mt-2 rounded-xl bg-emerald-50 px-4 py-3 flex items-center justify-between">
                      <p className="text-xs font-extrabold text-emerald-700">
                        Total Earnings (Gross)
                      </p>
                      <p className="text-sm font-extrabold text-emerald-800 tabular-nums">
                        {money(totals.earn)}
                      </p>
                    </div>
                  </div>
                </div>

                <div className="rounded-2xl border bg-white overflow-hidden">
                  <div className="px-4 py-3 border-b bg-rose-50">
                    <p className="text-xs font-extrabold text-rose-700 uppercase">
                      Deductions
                    </p>
                  </div>
                  <div className="p-4 space-y-3">
                    {(data?.deductions || []).map((item) => (
                      <div
                        key={item.label}
                        className="flex items-center justify-between text-sm"
                      >
                        <p className="text-slate-600 font-semibold">
                          {item.label}
                        </p>
                        <p className="text-rose-600 font-extrabold tabular-nums">
                          -{money(item.value)}
                        </p>
                      </div>
                    ))}
                    <div className="mt-2 rounded-xl bg-rose-50 px-4 py-3 flex items-center justify-between">
                      <p className="text-xs font-extrabold text-rose-700">
                        Total Deductions
                      </p>
                      <p className="text-sm font-extrabold text-rose-800 tabular-nums">
                        -{money(totals.ded)}
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="rounded-2xl border bg-white p-4">
                <div className="flex items-center gap-2">
                  <CalendarDays size={16} className="text-indigo-600" />
                  <p className="text-xs font-extrabold text-slate-900 uppercase">
                    Attendance Summary
                  </p>
                </div>

                <div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">
                  <Pill
                    label="Total Working Days"
                    value={data?.attendance?.working ?? "-"}
                  />
                  <Pill
                    label="Days Present"
                    value={data?.attendance?.present ?? "-"}
                  />
                  <Pill
                    label="Paid Leave"
                    value={data?.attendance?.paidLeave ?? "-"}
                  />
                  <Pill
                    label="Loss of Pay (LOP) Days"
                    value={data?.attendance?.lop ?? "-"}
                  />
                </div>
              </div>

              <div className="rounded-2xl border bg-white p-4">
                <div className="flex items-center gap-2">
                  <CheckCircle2 size={16} className="text-indigo-600" />
                  <p className="text-xs font-extrabold text-slate-900 uppercase">
                    Net Pay Summary
                  </p>
                </div>

                <div className="mt-3 space-y-3">
                  <div className="flex items-center justify-between text-sm">
                    <p className="text-slate-600 font-semibold">
                      Total Earnings
                    </p>
                    <p className="text-slate-900 font-extrabold tabular-nums">
                      {money(totals.earn)}
                    </p>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                    <p className="text-slate-600 font-semibold">
                      Total Deductions
                    </p>
                    <p className="text-rose-600 font-extrabold tabular-nums">
                      -{money(totals.ded)}
                    </p>
                  </div>

                  <div className="mt-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-center">
                    <p className="text-[10px] font-bold text-emerald-700 uppercase">
                      Net Pay
                    </p>
                    <p className="mt-1 text-2xl font-extrabold text-emerald-800 tabular-nums">
                      {money(totals.net)}
                    </p>
                    <p className="mt-1 text-[10px] font-semibold text-emerald-700/80 italic">
                      Rupees {numberToWords(totals.net)} Only
                    </p>
                  </div>
                </div>
              </div>

              <div className="rounded-2xl border bg-white p-4">
                <div className="flex items-center gap-2">
                  <Building2 size={16} className="text-indigo-600" />
                  <p className="text-xs font-extrabold text-slate-900 uppercase">
                    Payment Details
                  </p>
                </div>

                <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-3">
                  <div>
                    <p className="text-[10px] font-bold text-slate-500">
                      Account Holder
                    </p>
                    <p className="text-sm font-extrabold text-slate-900">
                      {data?.bank?.holder || "-"}
                    </p>
                  </div>
                  <div>
                    <p className="text-[10px] font-bold text-slate-500">
                      Bank Name
                    </p>
                    <p className="text-sm font-extrabold text-slate-900">
                      {data?.bank?.name || "-"}
                    </p>
                  </div>
                  <div>
                    <p className="text-[10px] font-bold text-slate-500">
                      Account Number
                    </p>
                    <p className="text-sm font-extrabold text-slate-900">
                      {data?.bank?.account || "-"}
                    </p>
                  </div>
                  <div>
                    <p className="text-[10px] font-bold text-slate-500">
                      IFSC Code
                    </p>
                    <p className="text-sm font-extrabold text-slate-900">
                      {data?.bank?.ifsc || "-"}
                    </p>
                  </div>
                  <div>
                    <p className="text-[10px] font-bold text-slate-500">
                      Branch
                    </p>
                    <p className="text-sm font-extrabold text-slate-900">
                      {data?.bank?.branch || "-"}
                    </p>
                  </div>
                  <div>
                    <p className="text-[10px] font-bold text-slate-500">Paid On</p>
                    <p className="text-sm font-extrabold text-slate-900">
                      {formatMonthDisplay(data?.bank?.paidOn) || "-"}
                    </p>
                  </div>
                </div>
              </div>

              <div className="flex flex-wrap gap-2">
                {/* Download PDF button removed as per request */}


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
